// config.js

// SUPABASE BAĞLANTI BİLGİLERİ
export const SUPABASE_URL = "https://airmuygsltqecjdgxlfh.supabase.co";
export const SUPABASE_KEY = "sb_publishable_qdDgX_KWXDdDnEu8ljnF3w_9L4FDWso";

// DİL SÖZLÜĞÜ (TR / EN)
export const translations = {
    tr: {
        brandTitle: "💃 ATKK",
        title: "Arjantin Tango Kombinasyon Kütüphanesi",
        menuLibrary: "📚 Kütüphane",
        menuFavorites: "⭐ Pratik Listem",
        menuAddVideo: "➕ Yeni Video Ekle",
        searchPlaceholder: "Eğitmen, partner veya etiket (tag) ara...",
        filterBtn: "🔍 Filtrele",
        loading: "Veritabanı bağlantısı kuruluyor......",
        empty: "Kütüphaneniz henüz boş. <br> Sol menüden yeni video eklemeye başlayabilirsiniz! 💃🕺",
        emptyFav: "Pratik listeniz henüz boş. <br> Kartların üzerindeki yıldız (⭐) ikonuna basarak bu haftanın pratiklerini buraya toplayabilirsiniz!",
        error: "❌ Veritabanı bağlantısı başarısız oldu. Lütfen anahtarlarınızı kontrol edin.\",",
        role: "🎬 Rol",
        location: "📍 Ortam",
        watch: "🔗 Videoyu İzle →",
        langBtn: "🇬🇧 EN",
        formTitle: "➕ Yeni Video Kaydet",
        formTitleEdit: "✏️ Videoyu Düzenle",
        lblInstructor: "👤 Eğitmen Seçimi:",
        lblVideoUrl: "🔗 Video URL'si (Instagram, YouTube vb.):",
        lblRole: "🎬 Odaklanılan Rol:",
        lblPartner: "👥 Partner Adı (Opsiyonel):",
        lblTags: "🏷️ Kombinasyon Etiketleri (Chips):",
        tagsPlaceholder: "Etiket yazıp virgül (,) veya Enter'a basın...",
        lblDownloaded: "💾 Kütüphaneye İndirildi mi?",
        lblDriveUrl: "🎬 Google Drive Video Önizleme Linki:",
        btnSubmitVideo: "🚀 Kütüphaneye Kaydet",
        btnUpdateVideo: "💾 Değişiklikleri Kaydet",
        assistantTitle: "🤖 Akıllı Dosya Adı Asistanı",
        assistantText: "Eğer bu videoyu bilgisayarınıza indirecekseniz, arşiv bütünlüğü için aşağıdaki dosya adını kullanmanızı öneririm:",
        assistantAlert: "Lütfen önce bir eğitmen seçin...",
        lblNewInstructorName: "Eğitmen Adı:",
        insSuccess: "🎉 Eğitmen başarıyla eklendi!",
        insUpdateSuccess: "🎉 Eğitmen adı güncellendi!",
        insDeleteSuccess: "💥 Eğitmen ve eğitmene ait tüm videolar kütüphaneden silindi!",
        insAlert: "Lütfen bir eğitmen adı yazın.",
        deleteConfirm: "Bu eğitmeni silmek istediğinize emin misiniz? Bu eğitmene ait TÜM videolar da kalıcı olarak silinecektir!",
        btnAddIns: "Ekle",
        btnUpdateIns: "Güncelle",
        lblCoverUpload: "Kapak Görseli:",
        dropText: "📸 Buraya tıklayın ve ekran görüntüsünü Ctrl + V ile yapıştırın",
        uploading: "⏳ Görsel yükleniyor...",
        uploadError: "❌ Görsel Supabase Storage'a yüklenemedi!",
        allRoles: "Tüm Roller",
        leader: "Lider",
        follower: "Takipçi",
        both: "İkisi De",
        allLocations: "Tüm Ortamlar",
        drive: "💾 Google Drive",
        social: "🌐 Sosyal Medya",
        closeBtn: "Kapat",
        btnClearFavorites: "🗑️ Bu Haftanın Pratik Listesini Temizle",
        confirmClearFavs: "Bu haftaki pratik listenizdeki tüm yıldızları kaldırmak istediğinize emin misiniz?",
        confirmDeleteVideo: "Bu videoyu kütüphanenizden kalıcı olarak silmek istediğinize emin misiniz?",
        successDeleteVideo: "💥 Video başarıyla silindi!",
        editTagsTitle: "✏️ Etiketleri Düzenle",
        addTagPlaceholder: "Yeni etiket yazıp virgül koyun...",
        btnCardEdit: "✏️ Düzenle",
        btnCardDelete: "🗑️ Sil"
    },
    en: {
        brandTitle: "💃 ATKK",
        title: "Argentine Tango Combination Library",
        menuLibrary: "📚 Library",
        menuFavorites: "⭐ Practice List",
        menuAddVideo: "➕ Add New Video",
        searchPlaceholder: "Search instructor, partner or tags...",
        filterBtn: "🔍 Filter",
        loading: "Connecting to database......",
        empty: "Your library is empty yet. <br> You can start adding new videos from the left menu! 💃🕺",
        emptyFav: "Your practice list is empty. <br> You can gather this week's practices here by clicking the star (⭐) icon on the cards!",
        error: "❌ Database connection failed. Please check your keys.",
        role: "🎬 Role",
        location: "📍 Location",
        watch: "🔗 Watch Video →",
        langBtn: "🇹🇷 TR",
        formTitle: "➕ Save New Video",
        formTitleEdit: "✏️ Edit Video",
        lblInstructor: "👤 Select Instructor:",
        lblVideoUrl: "🔗 Video URL (Instagram, YouTube etc.):",
        lblRole: "🎬 Focused Role:",
        lblPartner: "👥 Partner Name (Optional):",
        lblTags: "🏷️ Combination Tags (Chips):",
        tagsPlaceholder: "Type tag and press comma (,) or Enter...",
        lblDownloaded: "💾 Downloaded to Local Library?",
        lblDriveUrl: "🎬 Google Drive Video Preview Link:",
        btnSubmitVideo: "🚀 Save to Library",
        btnUpdateVideo: "💾 Save Changes",
        assistantTitle: "🤖 Smart Filename Assistant",
        assistantText: "If you are going to download this video to your computer, I recommend using the following filename for archive integrity:",
        assistantAlert: "Please select an instructor first...",
        lblNewInstructorName: "Instructor Name:",
        insSuccess: "🎉 Instructor successfully added!",
        insUpdateSuccess: "🎉 Instructor name updated!",
        insDeleteSuccess: "💥 Instructor and all related videos deleted!",
        insAlert: "Please type an instructor name.",
        deleteConfirm: "Are you sure you want to delete this instructor? ALL videos belonging to this instructor will also be permanently deleted!",
        btnAddIns: "Add",
        btnUpdateIns: "Update",
        lblCoverUpload: "Cover Image:",
        dropText: "📸 Click here and paste the screenshot via Ctrl + V",
        uploading: "⏳ Image uploading...",
        uploadError: "❌ Image could not be uploaded to Supabase Storage!",
        allRoles: "All Roles",
        leader: "Leader",
        follower: "Follower",
        both: "Both",
        allLocations: "All Locations",
        drive: "💾 Google Drive",
        social: "🌐 Social Media",
        closeBtn: "Close",
        btnClearFavorites: "🗑️ Clear This Week's Practice List",
        confirmClearFavs: "Are you sure you want to remove all stars from this week's practice list?",
        confirmDeleteVideo: "Are you sure you want to permanently delete this video from your library?",
        successDeleteVideo: "💥 Video successfully deleted!",
        editTagsTitle: "✏️ Edit Tags",
        addTagPlaceholder: "Type new tag and put comma...",
        btnCardEdit: "✏️ Edit",
        btnCardDelete: "🗑️ Delete"
    }
};