// SUPABASE BAĞLANTI BİLGİLERİ
export const SUPABASE_URL = "https://airmuygsltqecjdgxlfh.supabase.co";
export const SUPABASE_KEY = "sb_publishable_qdDgX_KWXDdDnEu8ljnF3w_9L4FDWso";

// DİL SÖZLÜĞÜ (TR / EN)
export const translations = {
    tr: {
        brandTitle: "💃 ATKK",
        title: "Arjantin Tango Kombinasyon Kütüphanesi",
        menuLibrary: "📚 Kütüphane",
        menuAddVideo: "➕ Yeni Video Ekle",
        searchPlaceholder: "Eğitmen, hareket veya etiket ara...",
        filterBtn: "🔍 Filtrele",
        loading: "Veritabanı bağlantısı kuruluyor...",
        empty: "Kütüphaneniz henüz boş. <br> Sol menüden yeni video eklemeye başlayabilirsiniz! 💃🕺",
        error: "❌ Veritabanı bağlantısı başarısız oldu. Lütfen anahtarlarınızı kontrol edin.",
        role: "🎬 Rol",
        location: "📍 Ortam",
        watch: "🔗 Videoyu İzle →",
        langBtn: "🇬🇧 EN",
        formTitle: "➕ Yeni Video Kaydet",
        lblInstructor: "Eğitmen Seç / Ekle:",
        lblVideoUrl: "Video URL (Instagram Reels / YouTube Shorts vb.):",
        lblRole: "Rol Tipi:",
        lblPartner: "Partner Adı (İsteğe Bağlı):",
        lblDownloaded: "Google Drive'a Yedeklendi mi?",
        btnSubmitVideo: "💾 Veritabanına Kaydet",
        successSave: "🎉 Video ve kapak resmi başarıyla kütüphaneye eklendi!",
        lblNewInstructorName: "Eğitmen Adı:",
        insSuccess: "🎉 Eğitmen başarıyla eklendi!",
        insUpdateSuccess: "🎉 Eğitmen ismi güncellendi!",
        insDeleteSuccess: "💥 Eğitmen ve ona ait tüm videolar silindi!",
        insAlert: "Lütfen bir eğitmen adı yazın.",
        deleteConfirm: "Bu eğitmeni silmek istediğinize emin misiniz? Eğitmene ait TÜM videolar da kalıcı olarak silinecektir!",
        btnAddIns: "Ekle",
        btnUpdateIns: "Güncelle",
        lblCoverUpload: "Kapak Resmi (Hareketi görüyorken Win+Shift+S yapıp buraya tıklayıp Ctrl+V ile yapıştırın):",
        dropText: "📸 Buraya tıklayın ve Ctrl + V ile ekran görüntüsünü yapıştırın",
        uploading: "⏳ Resim yükleniyor...",
        uploadError: "❌ Resim Supabase Storage'a yüklenemedi! Lütfen kovanızın (bucket) Public olduğundan emin olun.",
        allRoles: "Tüm Roller",
        leader: "Lider",
        follower: "Takipçi",
        both: "İkisi de",
        allLocations: "Tüm Ortamlar",
        drive: "💾 Google Drive",
        social: "🌐 Sosyal Medya",
        btnConfirm: "Tamam",
        btnCancel: "İptal",
        notification: "Bildirim"
    },
    en: {
        brandTitle: "💃 ATKK",
        title: "Argentine Tango Combination Library",
        menuLibrary: "📚 Library",
        menuAddVideo: "➕ Add New Video",
        searchPlaceholder: "Search instructor, movement or tag...",
        filterBtn: "🔍 Filter",
        loading: "Connecting to database...",
        empty: "Your library is empty yet. <br> You can start adding new videos from the left menu! 💃🕺",
        error: "❌ Database connection failed. Please check your keys.",
        role: "🎬 Role",
        location: "📍 Storage",
        watch: "🔗 Watch Video →",
        langBtn: "🇹🇷 TR",
        formTitle: "➕ Save New Video",
        lblInstructor: "Select / Add Instructor:",
        lblVideoUrl: "Video URL (Instagram Reels / YouTube Shorts etc.):",
        lblRole: "Role Type:",
        lblPartner: "Partner Name (Optional):",
        lblDownloaded: "Backed up to Google Drive?",
        btnSubmitVideo: "💾 Save to Database",
        successSave: "🎉 Video successfully added!",
        lblNewInstructorName: "Instructor Name:",
        insSuccess: "🎉 Instructor successfully added!",
        insUpdateSuccess: "🎉 Instructor name updated!",
        insDeleteSuccess: "💥 Instructor and all related videos deleted!",
        insAlert: "Please type an instructor name.",
        deleteConfirm: "Are you sure you want to delete this instructor? ALL videos belonging to this instructor will also be permanently deleted!",
        btnAddIns: "Add",
        btnUpdateIns: "Update",
        lblCoverUpload: "Cover Image (Take screenshot with Win+Shift+S, click here and paste with Ctrl+V):",
        dropText: "📸 Click here and paste the screenshot via Ctrl + V",
        uploading: "⏳ Image uploading...",
        uploadError: "❌ Image could not be uploaded to Supabase Storage!",
        allRoles: "All Roles",
        leader: "Leader",
        follower: "Follower",
        both: "Both",
        allLocations: "All Locations",
        drive: "💾 Google Drive",
        social: "🌐 Social Media",
        btnConfirm: "OK",
        btnCancel: "Cancel",
        notification: "Notification"
    }
};