// SUPABASE BAĞLANTI BİLGİLERİ
export const SUPABASE_URL = "https://airmuygsltqecjdgxlfh.supabase.co";
export const SUPABASE_KEY = "sb_publishable_qdDgX_KWXDdDnEu8ljnF3w_9L4FDWso";

// DİL SÖZLÜĞÜ (TR / EN)
export const translations = {
    tr: {
        brandTitle: "💃 ATKK",
        title: "Arjantin Tango Kombinasyon Kütüphanesi",
        menuLibrary: "📚 Kütüphane",
        menuFavorites: "⭐ Pratik Listem",
        menuAddVideo: "➕ Yeni Video Ekle",
        searchPlaceholder: "Eğitmen, partner veya etiket (tag) ara...",
        filterBtn: "🔍 Filtrele",
        loading: "Veritabanı bağlantısı kuruluyor......",
        empty: "Kütüphaneniz henüz boş. <br> Sol menüden yeni video eklemeye başlayabilirsiniz! 💃🕺",
        emptyFav: "Pratik listeniz henüz boş. <br> Kartların üzerindeki yıldız (⭐) ikonuna basarak bu haftanın pratiklerini buraya toplayabilirsiniz!",
        error: "❌ Veritabanı bağlantısı başarısız oldu. Lütfen anahtarlarınızı kontrol edin.",
        role: "🎬 Rol",
        location: "📍 Ortam",
        watch: "🔗 Videoyu İzle →",
        langBtn: "🇬🇧 EN",
        formTitle: "➕ Yeni Video Kaydet",
        lblInstructor: "Eğitmen Seçimi:",
        btnManageInstructors: "⚙️ Eğitmenleri Yönet",
        lblPartner: "Partner (Opsiyonel):",
        lblVideoUrl: "Video URL (Drive veya Sosyal Medya):",
        lblRole: "Rolü Seçin:",
        lblLocation: "Ortamı Seçin:",
        lblTags: "Etiketler (Tag'ler):",
        addTagPlaceholderForm: "Etiket yazıp enter veya virgüle basın...",
        btnSubmitVideo: "💾 Videoyu Kütüphaneye Ekle",
        btnUpdateVideo: "🔄 Değişiklikleri Kaydet",
        modalInsTitle: "⚙️ Eğitmen Yönetim Paneli",
        lblSelectInstructor: "Mevcut Eğitmeni Düzenle / Sil:",
        btnEditInsName: "✏️ İsmi Düzenle",
        btnDeleteIns: "🗑️ Eğitmeni ve Videolarını Sil",
        lblNewInstructorName: "Eğitmen Adı:",
        insSuccess: "🎉 Eğitmen başarıyla eklendi!",
        insUpdateSuccess: "🎉 Eğitmen adı güncellendi!",
        insDeleteSuccess: "💥 Eğitmen ve eğitmene ait tüm videolar silindi!",
        insAlert: "Lütfen bir eğitmen adı yazın.",
        deleteConfirm: "Bu eğitmeni silmek istediğinize emin misiniz? Bu eğitmene ait TÜM videolar da kalıcı olarak silinecektir!",
        btnAddIns: "Ekle",
        btnUpdateIns: "Güncelle",
        lblCoverUpload: "Kapak Görseli:",
        dropText: "📸 Buraya tıklayın ve Ctrl + V ile ekran görüntüsü yapıştırın",
        uploading: "⏳ Görsel yükleniyor...",
        uploadError: "❌ Görsel Supabase Storage alanına yüklenemedi!",
        allRoles: "Tüm Roller",
        leader: "Leader",
        follower: "Follower",
        both: "Both",
        allLocations: "Tüm Ortamlar",
        drive: "💾 Google Drive",
        social: "🌐 Sosyal Medya",
        closeBtn: "Kapat",
        btnClearFavorites: "🗑️ Bu Haftanın Pratik Listesini Temizle",
        confirmClearFavs: "Bu haftanın pratik listesindeki tüm yıldızları kaldırmak istediğinize emin misiniz?",
        confirmDeleteVideo: "Bu videoyu kütüphanenizden kalıcı olarak silmek istediğinize emin misiniz?",
        successDeleteVideo: "💥 Video başarıyla silindi!",
        editTagsTitle: "✏️ Etiketleri Düzenle",
        addTagPlaceholder: "Yeni etiket yazıp virgül koyun...",
        btnCardEdit: "✏️ Düzenle",
        btnCardDelete: "🗑️ Sil"
    },
    en: {
        brandTitle: "💃 ATKK",
        title: "Argentine Tango Combination Library",
        menuLibrary: "📚 Library",
        menuFavorites: "⭐ Practice List",
        menuAddVideo: "➕ Add New Video",
        searchPlaceholder: "Search instructor, partner or tag...",
        filterBtn: "🔍 Filter",
        loading: "Connecting to database...",
        empty: "Your library is empty yet. <br> You can start adding new videos from the left menu! 💃🕺",
        emptyFav: "Your practice list is empty yet. <br> Click the star (⭐) icon on cards to collect this week's practices here!",
        error: "❌ Database connection failed. Please check your keys.",
        role: "🎬 Role",
        location: "📍 Location",
        watch: "🔗 Watch Video →",
        langBtn: "🇹🇷 TR",
        formTitle: "➕ Save New Video",
        lblInstructor: "Select Instructor:",
        btnManageInstructors: "⚙️ Manage Instructors",
        lblPartner: "Partner (Optional):",
        lblVideoUrl: "Video URL (Drive or Social Media):",
        lblRole: "Select Role:",
        lblLocation: "Select Location:",
        lblTags: "Tags:",
        addTagPlaceholderForm: "Type tag and press enter or comma...",
        btnSubmitVideo: "💾 Add Video to Library",
        btnUpdateVideo: "🔄 Save Changes",
        modalInsTitle: "⚙️ Instructor Management Panel",
        lblSelectInstructor: "Edit / Delete Existing Instructor:",
        btnEditInsName: "✏️ Edit Name",
        btnDeleteIns: "🗑️ Delete Instructor & Videos",
        lblNewInstructorName: "Instructor Name:",
        insSuccess: "🎉 Instructor successfully added!",
        insUpdateSuccess: "🎉 Instructor name updated!",
        insDeleteSuccess: "💥 Instructor and all related videos deleted!",
        insAlert: "Please type an instructor name.",
        deleteConfirm: "Are you sure you want to delete this instructor? ALL videos belonging to this instructor will also be permanently deleted!",
        btnAddIns: "Add",
        btnUpdateIns: "Update",
        lblCoverUpload: "Cover Image:",
        dropText: "📸 Click here and paste the screenshot via Ctrl + V",
        uploading: "⏳ Image uploading...",
        uploadError: "❌ Image could not be uploaded to Supabase Storage!",
        allRoles: "All Roles",
        leader: "Leader",
        follower: "Follower",
        both: "Both",
        allLocations: "All Locations",
        drive: "💾 Google Drive",
        social: "🌐 Social Media",
        closeBtn: "Close",
        btnClearFavorites: "🗑️ Clear This Week's Practice List",
        confirmClearFavs: "Are you sure you want to remove all stars from this week's practice list?",
        confirmDeleteVideo: "Are you sure you want to permanently delete this video from your library?",
        successDeleteVideo: "💥 Video successfully deleted!",
        editTagsTitle: "✏️ Edit Tags",
        addTagPlaceholder: "Type new tag and put comma...",
        btnCardEdit: "✏️ Edit",
        btnCardDelete: "🗑️ Delete"
    }
};